use sqlx::FromRow;
use time::PrimitiveDateTime;

#[derive(Debug, FromRow, PartialEq)]
struct TableA {
    #[sqlx(rename = "ID")]
    id: i32,
    #[sqlx(rename = "NAME")]
    name: String,
    #[sqlx(rename = "DOB")]
    dob: Option<PrimitiveDateTime>,
    #[sqlx(rename = "IS_PROCESSED")]
    is_processed: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use sqlx::Row;
    use sqlx::postgres::PgPoolOptions;
    use std::env;

    #[tokio::test]
    async fn test_sqlx() -> Result<(), sqlx::Error> {
        let database_url = env::var("DATABASE_URL")
            .unwrap_or_else(|_| "postgres://user1:password1@localhost:5432/postgresdb".to_string());

        let pool = PgPoolOptions::new()
            .max_connections(5)
            .connect(&database_url)
            .await?;

        println!("Connection pool created: {:?}", pool);

        let res = sqlx::query("select 1 + 2 as sum").fetch_one(&pool).await?;
        let sum: i32 = res.get("sum");
        println!("1 + 2 = {}", sum);

        let mut new_record = TableA {
            id: 0, // Placeholder, will be overwritten by the id generated by the database.
            name: "another test".to_string(),
            dob: Some(time::macros::datetime!(2025-08-17 13:01:02.345)),
            is_processed: Some("Y".to_string()),
        };

        // Insert the record and get the generated ID back
        new_record.id = sqlx::query_scalar("INSERT INTO TABLE_A (NAME, DOB, IS_PROCESSED) VALUES ($1, $2, $3) RETURNING id")
            .bind(&new_record.name)
            .bind(&new_record.dob)
            .bind(&new_record.is_processed)
            .fetch_one(&pool)
            .await?;

        // update

        let inserted_record =
            sqlx::query_as!(TableA, "SELECT * FROM TABLE_A WHERE ID = $1", new_record.id)
                .fetch_one(&pool)
                .await?;

        assert_eq!(new_record, inserted_record);

        println!("Inserted record: {:?}", inserted_record);

        Ok(())
    }
}
